### PR TITLE
Renaming interleave to interleave-mode

### LINKED ISSUE #22: Naming convention cleanup?
Hi,

I was revisiting interleave.el, and wanted to clean up the naming of various funcitons and the interleave minor mode.

(1) Rename `interleave` minor mode to `interleave-mode` 

Right now we get this warning:

> Compiling file /home/kmodi/.emacs.d/forks-unused/interleave/interleave.el at Sun Aug 21 23:44:38 2016
> interleave.el:439:1:Warning: global/dynamic var ‘interleave’ lacks a prefix

It is a convention to name a minor mode ending with `-mode`. Also I have verified that renaming as above gets rid of that warning when byte-compiling interleave.el. That would mean a backward incompatible change.  But the `interleave` name can be marked as obsolete and then later removed after few months if you like.

(2) Remove `--` from the names of commands meant to be used by the end-user.

The convention is to use `--` only for the functions that are used internally, and definitely not for the interactive functions aka commands. Would you want to refactor the code so that `interleave--` is used solely for internal functions.

If you'd like I can send a PR for these changes.

### PR DESCRIPTION
**Pull request by rudolfochrist**
(don't let the branch name `minor-changes` distract you, but...)

Changes this PR introduce:
- Renaming of `interleave` to `interleave-mode`.
- Refactoring the public interface. Commands and variables were renamed to not use the "--" convetion that indicates internal-use only. Marking the old function and variables names as obsolote. Perhaps they get removed once we hit 2.0. 
- Refactoring/extending Makefile
- Adding simple integration tests. The tests don't cover all code but test the core functionality. 
- Adjusting docstrings as well as general documentation.

This PR resolves #22 and #19. 

@kaushalmodi 
Can you do me a favor and review this PR? Thanks in advance.

### CODE REVIEW

**Comment by kaushalmodi** [comment]
That looks like a big healthy patch. Is it OK if I take a week to review it?

**Comment by rudolfochrist** [comment]
Of course.

**Comment by kaushalmodi** [comment]
It took longer than I wanted to get to this.

I checked out the experimental branch and it works great except for this one thing..

If the point (▯) in the .org file is at 

```
#+INTERLEAVE_PDF: somefile.pdf
▯
* Notes for page 20
```

And then if I do `M-x interleave-sync-pdf-page-next`, I get something like

> org-back-to-heading: Before first headline at position 74 in buffer ..

It feels like dejavu and I believe I have fixed this somewhere. But in any case, this shouldn't stop you from releasing this as the workaround is to first bring the point manually under one of the headings.

**Comment by rudolfochrist** [comment]
Thanks @kaushalmodi for reviewing this. I think a spent another week using this branch and see if I run into problems.

**Pull request merged**
