### PR TITLE
Change all command names to be public functions

### PR DESCRIPTION
**Pull request by NicolasPetton**
This PR changes all command and custom variable names that were private (using double dash in the name) to be public.

### CODE REVIEW

**Comment by rudolfochrist** [comment]
Hi,

thanks for your PR. Could you provide some rationale why you think the functions should be public? Till now they are kept intentionally private. Thank you.

**Comment by NicolasPetton** [comment]
Sebastian Christ writes:

> Hi,
> 
> thanks for your PR. Could you provide some rationale why you think the
> functions should be public? Till now they are kept intentionally
> private. Thank you.

Sure,

Command functions are supposed to be executed by the user (using `M-x`),
that's why they should be public.  Private functions should not be
exposed to the user.

The same goes for custom variables: they should not be private, as the
user is supposed to customize them.

Cheers,

## Nico

Nicolas Petton
http://nicolas-petton.fr

**Comment by rudolfochrist** [comment]
So, you think that some users navigate (e.g.) with `M-x interleave-go-to-next-page` instead of typing <kbd>n</kbd>?

**Comment by NicolasPetton** [comment]
Sebastian Christ writes:

> So, you think that some users navigate (e.g.) with `M-x
> interleave-go-to-next-page` instead of typing <kbd>n</kbd>?

It's not really about _if_ they will do, but that they can.

As a general rule, user-visible functions should be public.  After all,
how can they be private if they're exposed to the end-user?

## Nico

Nicolas Petton
http://nicolas-petton.fr

**Comment by rudolfochrist** [comment]
Yes. Sounds legit. In the end it is more consistent this way. I'll do some testing and merge it later that day. Thank you.

S.

**Pull request merged**
